### PR TITLE
add full gc collection every teardown

### PR DESCRIPTION
**Pull request by sinkingsugar**
Welcome to the garbage collected reality

### CODE REVIEW

**Comment by dryajov** [comment]
Interesting, this doesn't seem to be the issue after all, tests still fail in the same place.

**Comment by sinkingsugar** [comment]
`SIGSEGV` is the GC issue

**Comment by sinkingsugar** [comment]
Ah sorry, forcing full collect is just to make sure it crashes 100% 😄 and avoid catching it in the future after months...

**Comment by sinkingsugar** [comment]
This branch is not a fix, just an improvement on how tests test things basically.

**Pull request closed without merging**
