### PR TITLE
clean up peerid

### PR DESCRIPTION
**Pull request by arnetheduck**
* fix dangling cstring on error return
* remove some useless inlines
* less mallocs in shortlog
* proc -> func
* rename test

### CODE REVIEW

**Comment by arnetheduck** [comment]
I'm not sure what the azure issue is - looks unrelated?

**Comment by dryajov** [comment]
Is this just an optimization/cleanup or was there some specific issue this is trying to fix?

**Comment by dryajov** [comment]
The azure issue is unrelated but I've seen this fail sporadically a few times so I need to look into what's causing it.

**Comment by arnetheduck** [comment]
well, like the description says, it fixes a cstring pointing to a local string in a return type - the rest is mostly style fixes and a few minor optimizations

**Pull request merged**
