### PR TITLE
proper name for topics so that we can filter dynamically using chronicles

### PR DESCRIPTION
**Pull request by onqtam**

### CODE REVIEW

**Comment by sinkingsugar** [comment]
Ok... so that's why it never worked properly for me!

**Comment by arnetheduck** [comment]
while we're at it, shall we make the topics lowercase / similar to the module name?

**Comment by onqtam** [comment]
I made them all lowercase but in a few cases the topics don't match the file names (`coder.nim`, `lpchannel.nim`, `message.nim`), but I think that's fine...?

**Comment by arnetheduck** [comment]
yeah, it's probably better - should perhaps come up with some convention for nested modules but this is an improvement already

**Pull request merged**
