### PR TITLE
[WIP] Gossipsub Implementation

### PR DESCRIPTION
**Pull request by dryajov**
Do not review/merge yet. In progress.

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
Last commit hogged AppVeyor for a full hour for each arch, by getting stuck after 8 minutes.

**Comment by dryajov** [comment]
> Last commit hogged AppVeyor for a full hour for each arch, by getting stuck after 8 minutes.

you have any ideas as to why?

**Comment by stefantalpalaru** [comment]
No. The test suite just hanged in the same spot. I didn't debug it.

**Comment by cheatfate** [comment]
@dryajov, I'm curious why you marked this PR as [WIP] and asked not to review it yet, and now you just merged? There many questions left behind now...

**Comment by dryajov** [comment]
Mostly because this is a huge improvement over what's in master. 

This PR included a pretty big chunk of functionality alongside small improvements; keeping this branch around would mean either backporting those over to master (and keep going back and forth until this is merged) or merge it as is and break the improvements into their own (hopefully smaller) parallel branches/efforts. This also include some initial interop testing, which demonstrates that the stack is already interoperable with at least two other major implementations Go and Js. The interop tests are written on top of the go daemon (I've manually tested the JS impmentation, but to a lesser extent) and touch on basic connection establishing and upgrading as well as floodsub and gossipsub.

Merging this however does not preclude further improvement, please log any concerns/questions/suggestions as separate issues.

**Pull request merged**
