### PR TITLE
grab agentversion/protoversion

### PR DESCRIPTION
**Pull request by arnetheduck**

### CODE REVIEW

**Comment by arnetheduck** [comment]
bah, that identify log wasn't quite ready for prime time :scream:

**Comment by dryajov** [comment]
Hmm, but this shouldn't break anything, should it?

**Comment by arnetheduck** [comment]
it offends aesthetic sensibilities

**Comment by dryajov** [comment]
Lol - ok, I can relate 😛. 

That's why I also like using wip PR's now - hope the damage for this one was minimal.

**Pull request merged**
