### PR TITLE
Lazy channels

### PR DESCRIPTION
**Pull request by sinkingsugar**
https://github.com/status-im/nim-libp2p/issues/46

@dryajov let me know if you think this is a possible solution

### CODE REVIEW

**Comment by sinkingsugar** [comment]
I'm having an issue similar to https://github.com/nim-lang/Nim/issues/12673 now...
pinging: @mratsim @arnetheduck @zah 

Given this type:
https://github.com/sinkingsugar/nim-libp2p/blob/b31f794a47cf005cc8e88716cc1630ed84e120a7/libp2p/connection.nim#L20-L24
And this derived type:
https://github.com/sinkingsugar/nim-libp2p/blob/b31f794a47cf005cc8e88716cc1630ed84e120a7/libp2p/muxers/mplex/mplex.nim#L33
When I call:
https://github.com/sinkingsugar/nim-libp2p/blob/b31f794a47cf005cc8e88716cc1630ed84e120a7/libp2p/muxers/mplex/mplex.nim#L156-L159
If I receive it in a:
`let conn: Connection =` rather then `let conn =` with type deduction, basically all dynamic dispatch fails and calls are on `Connection` type.
I could not reproduce in a simpler test yet.

**Comment by sinkingsugar** [comment]
Also Lazyness should be optional, but the above issue prevents that to be done 😞

**Comment by dryajov** [comment]
This shouldn't be done in `Connection`, instead we should move the logic to `LPChannel` and mplex itself. I would simply add the `isOpen` flag to `LPChannel` and then delay opening the channel on first write.

**Comment by sinkingsugar** [comment]
Hmm, the idea was that you could figure if this was lazy or not using `x of LazyConnection` or so, but if you think that is not necessary moving to `LPChannel` is fine too! 
Still would you specify *is lazy* in `newStream` tho?

**Comment by zah** [comment]
The discussion left me a bit confused. In the end, is there a method dispatching issue in Nim and is it a blocker for the goals here?

**Comment by sinkingsugar** [comment]
@zah sorry, there is a issue indeed, but for this PR is not an issue anymore.

**Comment by sinkingsugar** [comment]
Re-opeming from main repo

**Pull request closed without merging**
