### PR TITLE
Gossipsub: don't relay message to source

### PR DESCRIPTION
**Pull request by Menduist**

### CODE REVIEW

**Comment by dryajov** [comment]
The daemon is failing on linux 386... Seems to be the same sporadic issue we've seen before. I wonder if we're simply timing out on connects? Perhaps we can bump/add some sleeps to allow connections to get established and see if this affects the failure rate?

**Comment by Menduist** [comment]
Already tried to sleep, no effect unfortunately :/
When it fails, it succeeds to connect, but the peers don't see that they are both members of the topic.

I'll create a PR with my various test if you want to take a look

Also I noticed here that it failed some times on Gossipsub, and other times on pubsub. Fun

**Comment by Menduist** [comment]
Uh, I guess there was no actual issues with it, just unlucky CI

**Comment by Menduist** [comment]
Closed in favor of #648

**Pull request closed without merging**
