### PR TITLE
debug prints

### PR DESCRIPTION
**Pull request by stefantalpalaru**
Stream IDs and more tracing.

### CODE REVIEW

**Comment by dryajov** [comment]
Is there any way we can set this field only when logging is enabled? Does chronicles has a suitable define that we can use to enable disable this?

**Comment by stefantalpalaru** [comment]
Why bother making the code uglier with conditional object fields and log scopes?

**Comment by dryajov** [comment]
> Why bother making the code uglier with conditional object fields and log scopes?

why have a useless object taking up memory when it's unneded?

**Comment by stefantalpalaru** [comment]
You're worried about an extra 12 bytes per stream? https://github.com/nim-lang/Nim/blob/7e83adff84be5d0c401a213eccb61e321a3fb1ff/lib/pure/oids.nim#L21

**Comment by dryajov** [comment]
Well, it's not just the extra bytes, but if we can avoid it would be definitely better. 

It's a matter of having the facility to enable/disable this sort of metadata in general. Since it's only is required if chronicles tracing is enabled, then there should be a way for us to control that with compile time defines?

**Comment by stefantalpalaru** [comment]
The logging level is usually selected at runtime. Object type fields are specified at compile time.

**Comment by dryajov** [comment]
> The logging level is usually selected at runtime. Object type fields are specified at compile time.

I guess it depends on how you use chronicles, I know that NBC has runtime flags for it, but the way that the chronicles docs are written, they encourage/emphasise compile time over runtime. 

It's fine if the selected logging mode at runtime doesn't match the one at compile time, but as long as we have a way of controlling it depending on the build flags, that should be ok.

**Comment by stefantalpalaru** [comment]
> the way that the chronicles docs are written, they encourage/emphasise compile time over runtime

Yes, but in practice both Nimbus and NBC ended up using runtime log level selection.

> as long as we have a way of controlling it depending on the build flags, that should be ok

You can simply check the value of "chronicles_log_level" (case-insensitive comparison needed). After doing that in all the right places, run `git diff` and notice the ugliness.

**Comment by zah** [comment]
`chronicles_log_level` is not public because it's not strongly typed. There is `enabledLogLevel` which is the following enum:

```nim
type
  LogLevel* = enum
    NONE,
    TRACE,
    DEBUG,
    INFO,
    NOTICE,
    WARN,
    ERROR,
    FATAL
```

**Comment by stefantalpalaru** [comment]
> chronicles_log_level is not public because it's not strongly typed

I was talking about the define with the same name.

**Comment by zah** [comment]
My understanding of the discussion above is that @dryajov is interested in checking the compile-time log level in the code. To do this, you have to use:

```nim
when chronicles.enabledLogLevel = TRACE:
  ...
```

**Comment by dryajov** [comment]
@zah thanks ! That's what I was looking for. @stefantalpalaru can we add that check please?

**Comment by stefantalpalaru** [comment]
Done.

**Pull request merged**
