### PR TITLE
investigate missing coverage

### PR DESCRIPTION
**Pull request by sinkingsugar**

### CODE REVIEW

**Comment by sinkingsugar** [comment]
@dryajov we were missing some folders , expect a big drop of coverage 😄 
I will try to make it less script error prone... not so easy with the way nim and cache works.

**Comment by sinkingsugar** [comment]
actually it should not drop much, was just missing the new gossip folders

**Comment by dryajov** [comment]
We have plenty of tests, by no means complete, but not terrible either :)

**Comment by dryajov** [comment]
> We have plenty of tests, by no means complete, but not terrible either :)

Let's work to increase it to > 90%.

**Pull request merged**
