### PR TITLE
adding validator timeout functionality

### PR DESCRIPTION
**Pull request by dryajov**

### CODE REVIEW

**Comment by arnetheduck** [comment]
this is a really odd feature - why should the library protect against broken validation code that runs for too long?

what kind of propagation in a gossip network will you get with a validation timeout of 1 minute?? given that gossip has memory of recently seen messages, why is 1 minute even reasonable? 

also, it assumes that the validation code hands back control to the async loop which is not a given, so it only protects against some kinds of slow validation procedures, but not synchronous ones.

**Comment by dryajov** [comment]
> this is a really odd feature - why should the library protect against broken validation code that runs for too long?

How so? The stack is use case agnostic and should guarantee to remain functional even in the face of incorrect user code, this is because we can't assume that there is going to be a one to one correspondence of consumers to the stack. What if we're running as a daemon and some rouge app registers a malicious validator? 

> what kind of propagation in a gossip network will you get with a validation timeout of 1 minute?? given that gossip has memory of recently seen messages, why is 1 minute even reasonable?

Remember that this runs per peer, so this wouldn't stop messages from other peers to propagate. The current `seen` cache is set to 2 minutes. But 1 minute might be too high, it's just an arbitrary number at this point - suggestions welcome.

> also, it assumes that the validation code hands back control to the async loop which is not a given, so it only protects against some kinds of slow validation procedures, but not synchronous ones.

Sure, you can always block the main loop in an async stack, there is nothing preventing that from happening. But a reasonable protection against slow or hanging user code, such as timing out, is better than silently hanging?

**Comment by dryajov** [comment]
Also, this is pretty standard - the Go implementation also employs a validation timeout - https://github.com/libp2p/go-libp2p-pubsub/blob/master/validation.go#L60.

**Comment by arnetheduck** [comment]
> But a reasonable protection

We have to assume that the user of the API is using it correctly - that includes writing validators that terminate, loops that have an exit condition, no Defects raised, etc etc.. like this, we're penalising correct code with superfluous checks - this may be appropriate in for example a browser that runs general javascript code that needs a failsafe against malicious input, but not validation code that is run on every single packet that arrives in a library tuned for resource-restricted environments where the additional overhead is undesirable.

> timing out, is better than silently hanging

Leaking in this case - the end result on the network is the same - packets don't get propagated. 

As an alternative, we could add a metric that keeps track of incoming packets as well as validated packets (or validations-in-flight or something - as well as number of unexpired timers etc) which would allow developers to monitor for odd behaviour..

**Comment by dryajov** [comment]
> We have to assume that the user of the API is using it correctly - that includes writing validators that terminate, loops that have an exit condition, no Defects raised, etc etc.. like this, we're penalising correct code with superfluous checks

You can always disable it if you don't need it by using `InfiniteDuration` - this makes sense from a general purpose networking stack perspective.

> Leaking in this case - the end result on the network is the same - packets don't get propagated.

This is precisely to prevent packets from being silently withheld by hanging validators. By raising and logging, we can make this evident rather than a hidden side effect of a bad validator.

> As an alternative, we could add a metric that keeps track of incoming packets as well as validated packets (or validations-in-flight or something - as well as number of unexpired timers etc) which would allow developers to monitor for odd behaviour..

I don't see why the two solutions can't coexist. We can do both.

**Comment by arnetheduck** [comment]
> I don't see why the two solutions can't coexist.

they can, but they each have a performance, complexity and maintenance price - no point in having two features serving the same need - metrics weighs less in all those areas.

How about we keep this feature in view and add it at a later date if it's shown to actually happen in the wild in a setting which wouldn't be made visible by metrics?

**Comment by dryajov** [comment]
> How about we keep this feature in view and add it at a later date if it's shown to actually happen in the wild in a setting which wouldn't be made visible by metrics?

Metrics aren't implemented yet and it is a more complex and _"harder to get right"_ feature that require tweaking and tuning before we settle on a comprehensive and useful set of parameters. Timeouts are already implemented and are an overall low overhead feature in terms of maintenance and complexity. 

Since we already have timers we can experiment and tweak them as we go. If we find that this feature doesn't work under some specific environment, it can always be disabled with the `InfiniteDuration` parameter. In short, I don't see any disadvantage of including this feature since it's already here vs putting it in the backburner for a feature that hasn't even been triaged yet.

I say we merge this and see how it goes, if we find that it doesn't work under some circumstances (or at all), we can always disable it with the `InfiniteDuration` parameter.

**Comment by arnetheduck** [comment]
> Metrics aren't implemented yet and it is a more complex and "harder to get right" feature 

I'm not sure I follow how metrics are more complex - from the point of view of the libp2p code, metrics are stateless and thus inherently more simple - this is why they are such a powerful tool. timers add complex state which results in overhead in this code - metrics moves the complexity elsewhere ensuring that the libp2p code remains clean. 

whatever - if you feel strongly about this, go ahead - the strongest argument for so far is: "would hypothetically be nice in case someone writes a bad validator and doesn't know how to debug it so it's reasonable to pay a per-packet cost for it" - when you wonder why browsers take up so much resources, it's well-intentioned features like these :)

**Comment by arnetheduck** [comment]
> Remember that this runs per peer, so this wouldn't stop messages from other peers to propagate. The current seen cache is set to 2 minutes. But 1 minute might be too high, it's just an arbitrary number at this point - suggestions welcome.

`Infinite`? 

there are no reasonable defaults here because it's application-dependent what constitutes a meaningful validation time.. as a debugging help, 1 minute is too low because there are correct cases where more than 1 minute is ok, and you don't want false positives from debugging helps - specially in light of the seen cache and validation times not necessarily being constant-time - thus a lower bound would be the seen-cache-timeout.

**Comment by dryajov** [comment]
> whatever - if you feel strongly about this, go ahead 

Great, lets try it out, if it doesn't work we'll get rid of it - I promise.

**Comment by arnetheduck** [comment]
> if it doesn't work

you won't notice it not working because when your code is correct, the feature doesn't do anything except waste a bit of resources which you won't notice on your developer machine, and add a bit of maintenance which developers like because it lets them keep their job :) the better question would be "did it actively help" - so far, there is no indication that poorly written validators are a real issue (yagni) because.. er.. well.. if your validator is taking up a lot of CPU time, we _will_ notice it in so many other ways - like for example the entire event loop being stuck for _a minute_ per the default here.. that's really really hard to not notice.

**Comment by zah** [comment]
I must side with Jacek here. Such timeouts would have been appropriate if the API was aiming at end users who can enter arbitrary validation rules through a scripting language. Otherwise, it feels like a violation of the [Fail-fast principle](https://en.wikipedia.org/wiki/Fail-fast). The author of the validation callback will be more aware of the particular timing risks in each situation and she can select the most appropriate timeout logic there (different validations can use different logic).

**Comment by dryajov** [comment]
I'm closing this for now since the consensus seems to be that this isn't necessary, plus timers have inherent issues in chronos right now, which makes for a case to minimize their use.

**Pull request closed without merging**
