### PR TITLE
Gossip stateful tests

### PR DESCRIPTION
**Pull request by sinkingsugar**
requires `identify-metrics` branch #458

### CODE REVIEW

**Comment by dryajov** [comment]
@sinkingsugar can we split the PR into metrics and testing? 

I would also note that I'm not sure about testing approach in general, I would have thought we'd use a similar approach to the already existing tests in https://github.com/status-im/nim-libp2p/blob/master/tests/pubsub/testgossipinternal.nim?

**Comment by arnetheduck** [comment]
> similar approach to the already existing tests

I find this approach a bit dubious - an alternative idea would be to extract a pure, non-async gossip-and-mesh data structure that could be tested independently and without all the mess - gossipsub would then be a thin async shell around this core.

**Comment by dryajov** [comment]
> > similar approach to the already existing tests
> 
> I find this approach a bit dubious - an alternative idea would be to extract a pure, non-async gossip-and-mesh data structure that could be tested independently and without all the mess - gossipsub would then be a thin async shell around this core.

Yeah, I agree not a bad idea overall. We've lots of tech debt and a cleanup and refactor is in order either way.

**Comment by sinkingsugar** [comment]
I'm a bit surprised about your opinions, this approach is exactly inspired by metrics and the way they showed issues to me.
It's simple and requires no artificial code at all.
Can you please enlighten me on what is wrong with it?

**Comment by sinkingsugar** [comment]
> @sinkingsugar can we split the PR into metrics and testing?

Well it's based on the metrics to not miss locations but yeah will do.

**Comment by sinkingsugar** [comment]
> @sinkingsugar can we split the PR into metrics and testing?
> 
> I would also note that I'm not sure about testing approach in general, I would have thought we'd use a similar approach to the already existing tests in https://github.com/status-im/nim-libp2p/blob/master/tests/pubsub/testgossipinternal.nim?

I don't like that approach so much personally, it's not abstract nor reflective, every time a change in the main code is done, a fix in the test (and there are not tests for the test) is needed.

**Comment by dryajov** [comment]
> I don't like that approach so much personally, it's not abstract nor reflective, every time a change in the main code is done, a fix in the test (and there are not tests for the test) is needed.

Yes, I agree that this isn't ideal either and that's why I completely agree with @arnetheduck that we need a refactor that will most of all benefit testing. By splitting gossip into several components it will allow us to test them in isolation without having to resort to the sort of hacks that this PR and admittedly the internal tests are attempting to workaround.

**Pull request closed without merging**
