### PR TITLE
Feat/conn cleanup

### PR DESCRIPTION
**Pull request by dryajov**
Backporting proper connection cleanup from #36 to align with latest chronos changes.

### CODE REVIEW

**Comment by cheatfate** [comment]
@dryajov, sorry but there no `chronos` changes which affects bug with incorrect stream usage. The only problem was there https://github.com/status-im/nim-libp2p/blob/master/libp2p/protocols/secure/secio.nim#L407 .

Initially when code was catching `Exception`, it is hided `Defect` https://github.com/status-im/nim-chronos/blob/master/chronos/streams/asyncstream.nim#L87 . This `Defect` raises only when you try to read/write from closed stream.

```nim
except Exception as exc:
      trace "exception in secio", exc = exc.msg
      return
```

**Comment by dryajov** [comment]
@cheatfate the latest changes in chronos exposed the incorrect handling. Not sure what's your point?

**Comment by cheatfate** [comment]
@dryajov what changes?

**Comment by cheatfate** [comment]
https://github.com/status-im/nim-libp2p/commit/dde8c01448e0302c99c39fcd02ced88431a60d27 this commit and changes to `secio.nim` is actually what exposed the problem.

**Comment by dryajov** [comment]
@cheatfate the recent churn in chronos is what lead to this changes, you're correct to point out that the use of `CatchableError` is what ultimately exposed the issue. 👍

**Pull request merged**
