### PR TITLE
wip2

### PR DESCRIPTION
**Pull request by arnetheduck**
* simplify buffer reading
* minimal stream impl
* fix a bunch of issues when reading length prefixes
* play with EOF signalling

### CODE REVIEW

**Comment by arnetheduck** [comment]
#100 revamped

**Comment by sinkingsugar** [comment]
I like the changes but I fail to understand what these changes are supposed to "fix", this is more like shuffling/rewriting code around, which is good but should happen probably in a later release?

Well ok the `readOnce` change would be extremely welcome but I don't think it's gonna fix anything.

I know everyone hates `bufferstream` but thinking out of the box maybe it really is ugly but it has no real pressing issues.

In any case I really cannot follow the discord discussion related to this PR very well during the day (night) so would be nice if it happened more on github 🥂

**Comment by arnetheduck** [comment]
Alright, let's recap some of the issues with `BufferStream`:

* Code-reuse-by-inheritance - ie it implements a bunch of methods - like `read*` - with new bugs however - the read methods in `chronos` had bugs, and `BufferedStream` adds its own - it would be better to factor out this code in a way that can be reused in both `chronos` and `libp2p` - for example, the logic for detecting the end of a line or for looping-while-there's-not-enough-data is the same - otherwise, to reuse the code, you _have_ to inherit from `BufferStream`
* Buffers data - but _extremely inefficiently_ - for example, it fires a synchronization event on every byte read (https://github.com/status-im/nim-libp2p/blob/3b69cef2d224676bb2f75fea578a9bd240182ea0/libp2p/stream/bufferstream.nim#L141) - this causes practical issues down the road in NBC - it would be better if there was less buffer copying and less synchronization
* Synchronizes readers and writers with its own machinery of events, locks and futures - this code is already implemented in `chronos` in `AsyncQueue` and is difficult to debug, audit and understand - it would be better if we could reuse blocks that already exist - or if it didn't have to do this at all when it's not needed because it will save time when analyzing how data flows. 

Let's also see why `secio`/`noise` uses Bufferstream (let's leave `mplex` aside for now, to simplify the discussion):

* the `LPStream` interface contains many methods that are redundant / variations on the same theme and don't really add any new capabilities that couldn't be solved outside of the interface (basically, `LPStream` shouldn't have all these methods - there's no benefit)
* the read loop creates a backpressure problem that needs a solution - the OS already deals with this problem if you just leave the data in the socket, and better - it can refrain from sending acks causing the other end to slow down earlier: reading the data and putting it in an application buffer is strictly worse than leaving it in the OS buffer. The read loop increases complexity and decreases performance without any benefits. This argument can be extended to every "layer" - if a layer doesn't "need" a read loop, it shouldn't have one, because a read loop is a cost.
* The additional data flow makes `secio` and `noise` harder to audit and debug - this is an ongoing cost - every time there is a problem (and we have many: memory leaks, propagation of close events, error handling etc etc), each problem is magnified by every piece of unnecessary complexity in the pipeline

So, what's the aim of this branch? Simplification. It shows how we can:
* Remove some unnecessary complexity (fewer read loops, simpler data flow, less cross-task synchronization etc)
* Reuse existing components better
* Split up concerns (buffering, decoding, etc) so that each piece is smaller and naturally reusable - we can then use them to improve other parts of the codebase as well.

The reason for introducing them now is that it will help auditing and debugging the current protocols - as we as developing the next ones - it has already proven useful in that several issues were found simply because the more streamlined interface here caused the bugs to surface - it wouldn't have been possible to introduce them had this interface been in place. It is also a step in the right direction towards handling errors - for example because there's less code that can cause errors that subsequently need handling.

**Comment by arnetheduck** [comment]
Most of the items in here have been incorporated except the bufferstream work which can be left for another day

**Pull request closed without merging**
