### PR TITLE
call write until all is written out

### PR DESCRIPTION
**Pull request by dryajov**
Don't give up until all bytes are written. 

@cheatfate as I understand it, this api can do partial writes, does this look appropriate?

### CODE REVIEW

**Comment by cheatfate** [comment]
StreamTransport.write() attempts to write all bytes, but if it returns `0` or value less then number of bytes requested, it only means that connection is dead and there no reason to continue writing. It also can generate some OS specific exception.

**Comment by dryajov** [comment]
Apparently this does have an effect, doing some `echo` debugging reveals:

```
[Suite] Identify
WRITEN............... 20
WRITEN............... 16
WRITEN............... 20
WRITEN............... 16
WRITEN............... 392
  [OK] handle identify message
WRITEN............... 20
WRITEN............... 16
WRITEN............... 20
WRITEN............... 16
WRITEN............... 352
  [OK] handle failed identify
```

**Comment by dryajov** [comment]
also, this might explain our mysterious CI issues?

**Comment by dryajov** [comment]
never mind, false alarm.

**Pull request closed without merging**
