### PR TITLE
Mplex timeout & size limits

### PR DESCRIPTION
**Pull request by sinkingsugar**
See https://github.com/status-im/nim-libp2p/pull/74

### CODE REVIEW

**Comment by cheatfate** [comment]
Looks like you going to create new timer for every `readMsg()` and this can significantly affect performance of `nim-libp2p`.

**Comment by sinkingsugar** [comment]
Not sure I understand, I mean every `await` has hidden cost indeed but we still write async/await everywhere :)
You mean `await sleepAsync` specifically has a high cost?
What is a light weight way to do a timeout `select() do while` like? Cos then good old plain `c` definitely is the way to go!

**Comment by cheatfate** [comment]
To handle timers we are using `heapqueue.nim`. This means:

* add new timer is O(logN)
* process one timer is O(logN)
* delete/cancel one timer is O(logN) (but in our current implementation its O(NlogN) 

In your PR you proposing to create new timer for every possible request to `readMsg()`. So for some heavy downloading its possible to produce big amounts of timers.

You can ask @dryajov about some real tests and experiments with timers.

**Comment by dryajov** [comment]
This is true, timers are currently pretty broken in chronos and until we fix them we should abstain from their use. I would say we leave the timeout out all together from this PR until @cheatfate finishes fixing them in chronos. 

There is a related issue with `sleepAsync` being used as a synchronization primitive in certain places of the codebase, I'm working on cleaning this up, but running into issues with what seem to be deadlocks, which is why I originally opted to using them in the first place.

**Comment by sinkingsugar** [comment]
I'm completely aware that chronos and asyncdispatch is filled with references and heap allocations (very nicely amortized by the GC, good luck with ARC btw), but yeah on top of that timers seems particularly useless due to the current implementation.
Btw sounds like the implementation is inspired by windows implementation itself: https://docs.microsoft.com/en-us/windows/win32/sync/timer-queues?redirectedfrom=MSDN

But at the same time this issue should not be relevant to libp2p. 
Ignoring timeouts to me sounds like asking for trouble.
Once the dependency (chronos in this case) is fixed we will gain performance, cool, but until that day we should not be here ignoring issues or writing workarounds.
Btw why we removed the timeout on the connection itself? that one was what we needed here as well.

(workaround) I guess since this transport is TCP we could actually `await` subscribing to a close/err from the `recv` itself somehow ? 
Maybe chronos itself should implement a traditional yet cheap `select/fd` timeout if it's not doing it yet.

**Comment by cheatfate** [comment]
@dryajov timers are not "broken" in chronos. If the timers are broken in chronos, than timers is broken in `libuv` and `python#asyncio`. Current implementation of timers is not optimal for processing tens thousands of timers at one time, but it exactly not broken.

@sinkingsugar call to `select/fd` is absolutely not cheap its a syscall. If you think syscalls are cheap please google "the cost of syscall".

Also i don't see a reason why low and middle layers of libp2p should use timeouts for processing, is there any specification which regulates timeouts in multiplexing or in readLp/writeLp code?

**Comment by dryajov** [comment]
> Current implementation of timers is not optimal for processing tens thousands of timers at one time, but it exactly not broken.

That's what I mean by broken.

> Also i don't see a reason why low and middle layers of libp2p should use timeouts for processing, is there any specification which regulates timeouts in multiplexing or in readLp/writeLp code?

True, we should not rely on timers for synchronization and a fix is coming to remove them.

That said chronos should be able to handle tens of thousands of timers - this is exactly what chronos is for. There isn't anything inherently wrong with @sinkingsugar code, but we can't use it right now because chronos has perf issues when it comes to timers.

So the issue is twofold, 1) chronos can't handle moderate to large amounts of timers, 2) libp2p was using timers to synchronize processing in some cases, which is hiding a bug that I'm currently fixing.

**Comment by sinkingsugar** [comment]
@cheatfate I wrote a few commercial mmorpgs net code with `select/fd`, also btw are you you aware that every heap allocation is a syscall too? also any socket operation? and half of the things you call in chronos? with ARC likely every `newFuture` will be a syscall, unless there is a smart allocator behind.
So, yeah not sure who needs to google what here 😄 But honestly I would just avoid this attitude, I was just giving a solution to a problem.
Btw I didn't mean to call select for every stream if you meant that, I mean't more in chronos, but again with TCP is not necessary.

@dryajov Hmm not sure I get it exactly (as in how are we handling when remotes disappear) but well I will remove this timeout from this PR.
Btw I refer to the issue comment:
> streams would hang indefinitely if the remote dies unexpectedly or is too slow

**Comment by cheatfate** [comment]
For some reason all the modern mmorpg's could not handle 1000 players in one single shard, except EVE Online and only when everybody is ready. Maybe because most of the people not using `select/fd` since invention of `epoll/kqueue`.

Every heap allocation is not a syscall even in Nim, even `malloc()` call for small amount of bytes is not a syscall too.

If you think that TCP timeout options like `SO_RCVTIMEO/SO_SNDTIMEO` will be able to help you, then i wish to disappoint you, this options working only on `blocking` sockets, while we have only `non-blocking` sockets here.

**Comment by sinkingsugar** [comment]
well `epoll/kqueue/overlapped` all syscalls too anyway 😄 
anyway this completely not relevant anymore. 

No I did not mean timeouts at all, I meant that since we are using TCP we actually don't need any cos socket will be closed anyway by the OS when dropping. If one day we add UDP there might be issues tho. 
**So yeah I guess as it is is just fine. This PR can be closed like this.**

P.S.
Mmos could not handle more then xxx players cos limited bandwidth, cheap servers and lack of processing power (physics, logic), nothing to do with syscalls directly.

**Pull request merged**
